version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=karaoke
      - POSTGRES_USER=postgres # Cambia en producción
      - POSTGRES_PASSWORD=pass # Cambia en producción
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080" # Expone el puerto del backend
    environment:
      - DATABASE_URL=postgres://postgres:pass@db:5432/karaoke
      - YOUTUBE_API_KEY=TU_API_KEY_DE_YOUTUBE_AQUI
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: